export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";
export const SET_PROJECTS = "SET_PROJECTS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";

export const FETCH_STORIES_START = "FETCH_STORIES_START";
export const FETCH_STORIES_FAIL = "FETCH_STORIES_FAIL";
export const SET_STORIES = "SET_STORIES";
export const CREATE_STORY_SUCCESS = "CREATE_STORY_SUCCESS";
export const CREATE_STORY_FAIL = "CREATE_STORY_FAIL";
