export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";
export const SET_PROJECTS = "SET_PROJECTS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
